// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.utility;

import com.magilhub.printnats.desktop.render.compat.Bitmap;
import com.magilhub.printnats.desktop.render.compat.BitmapFactory;
import com.magilhub.printnats.desktop.render.compat.Matrix;
import com.magilhub.printnats.desktop.render.compat.Log;

import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.regex.Pattern;

public class Utils {

    private static final String LINEBREAK = "\n"; // or "\r\n";
    public static final  int DOUBLE_WIDTH = 2;
    public static final  int DOUBLE_HEIGHT = 1;
    public static final  int NORMAL = 0;
    public static final  int CUSTOM = 3;


    public static Bitmap compressBitmap(Bitmap srcBitmap, int maxLength) {
        Bitmap destBitmap = null;

        try {
            BitmapFactory.Options opts = new BitmapFactory.Options();
            byte[] srcBytes = bitmap2Bytes(srcBitmap);
            BitmapFactory.decodeByteArray(srcBytes, 0, srcBytes.length, opts);
            int srcWidth = opts.outWidth;
            int srcHeight = opts.outHeight;
            double ratio;
            int destWidth;
            int destHeight;
            if (srcWidth > srcHeight) {
                ratio = (double) (srcWidth / maxLength);
                destWidth = maxLength;
                destHeight = (int) ((double) srcHeight / ratio);
            } else {
                ratio = (double) (srcHeight / maxLength);
                destHeight = maxLength;
                destWidth = (int) ((double) srcWidth / ratio);
            }

            BitmapFactory.Options newOpts = new BitmapFactory.Options();
            newOpts.inSampleSize = (int) ratio + 1;
            newOpts.inJustDecodeBounds = false;
            newOpts.outHeight = destHeight;
            newOpts.outWidth = destWidth;
            destBitmap = BitmapFactory.decodeByteArray(srcBytes, 0, srcBytes.length, newOpts);
        } catch (Exception var12) {
        }

        return destBitmap;
    }

    public static byte[] readStream(InputStream inStream) throws Exception {
        byte[] buffer = new byte[1024];
        ByteArrayOutputStream outStream = new ByteArrayOutputStream();

        int len;
        while ((len = inStream.read(buffer)) != -1) {
            outStream.write(buffer, 0, len);
        }

        byte[] data = outStream.toByteArray();
        outStream.close();
        inStream.close();
        return data;
    }

    public static Bitmap getImageFromBytes(byte[] bytes, BitmapFactory.Options opts) {
        if (bytes != null) {
            return opts != null ? BitmapFactory.decodeByteArray(bytes, 0, bytes.length, opts) : BitmapFactory.decodeByteArray(bytes, 0, bytes.length);
        } else {
            return null;
        }
    }

    public static Bitmap zoomBitmap(Bitmap bitmap, int w, int h) {
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();
        Matrix matrix = new Matrix();
        float scaleWidth = (float) w / (float) width;
        float scaleHeight = (float) h / (float) height;
        matrix.postScale(scaleWidth, scaleHeight);
        Bitmap newBmp = Bitmap.createBitmap(bitmap, 0, 0, width, height, matrix, true);
        return newBmp;
    }

    public static byte[] bitmap2Bytes(Bitmap bm) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        bm.compress(Bitmap.CompressFormat.PNG, 100, baos);
        return baos.toByteArray();
    }

    public static File saveFileFromBytes(byte[] b, String outputFile) {
        BufferedOutputStream stream = null;
        File file = null;

        try {
            file = new File(outputFile);
            FileOutputStream fstream = new FileOutputStream(file);
            stream = new BufferedOutputStream(fstream);
            stream.write(b);
        } catch (Exception var13) {
            var13.printStackTrace();
        } finally {
            if (stream != null) {
                try {
                    stream.close();
                } catch (IOException var12) {
                    var12.printStackTrace();
                }
            }

        }

        return file;
    }

    public static int printBitmap2File(Bitmap bitmap, String filePath) {
        File file;
        if (filePath.endsWith(".png")) {
            file = new File(filePath);
        } else {
            file = new File(filePath + ".png");
        }

        try {
            FileOutputStream fos = new FileOutputStream(file);
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, fos);
            fos.close();
            return 0;
        } catch (Exception var4) {
            var4.printStackTrace();
            return -1;
        }
    }

    public static byte[] bitmap2PrinterBytes(Bitmap bitmap, int left) {
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();

        String hexString = Integer.toHexString(height);

        byte[] imgbuf = new byte[(width / 8 + left + 4) * height];
        byte[] bitbuf = new byte[width / 8];
        int[] p = new int[8];
        int s = 0;
        System.out.println("+++++++++++++++ Total Bytes: " + (width / 8 + 4) * height);

        for (int y = 0; y < height; ++y) {
            int n;
            for (n = 0; n < width / 8; ++n) {
                int m;
                for (m = 0; m < 8; ++m) {
                    if (bitmap.getPixel(n * 8 + m, y) == -1) {
                        p[m] = 0;
                    } else {
                        p[m] = 1;
                    }
                }

                m = p[0] * 128 + p[1] * 64 + p[2] * 32 + p[3] * 16 + p[4] * 8 + p[5] * 4 + p[6] * 2 + p[7];
                bitbuf[n] = (byte) m;
            }

            if (y != 0) {
                ++s;
                imgbuf[s] = 22;
            } else {
                imgbuf[s] = 22;
            }

            ++s;


            imgbuf[s] = (byte) (width / 8 + left);

            for (n = 0; n < left; ++n) {
                ++s;
                imgbuf[s] = 0;
            }

            for (n = 0; n < width / 8; ++n) {
                ++s;
                imgbuf[s] = bitbuf[n];
            }

            ++s;
            imgbuf[s] = 21;
            ++s;
            imgbuf[s] = 1;
        }

        Log.e("TAG", "bitmap2PrinterBytes: " + imgbuf.length);
        return imgbuf;
    }


    public static byte[] testImage(Bitmap bitmap, int left) {
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();

        Log.e("TAG", "bitmap2PrinterBytes: " + (width / 8 + left + 4) * height);

        String hexString = Integer.toHexString(height);
        int length = hexString.length();
        byte[] buffer = new byte[(length + 1) / 2];
        boolean evenByte = true;
        byte nextByte = 0;
        int bufferOffset = 0;

        if ((length % 2) == 1) {
            evenByte = false;
        }

        for (int i = 0; i < length; i++) {
            char c = hexString.charAt(i);
            int nibble; // A "nibble" is 4 bits: a decimal 0..15

            if ((c >= '0') && (c <= '9')) {
                nibble = c - '0';
            } else if ((c >= 'A') && (c <= 'F')) {
                nibble = c - 'A' + 0x0A;
            } else if ((c >= 'a') && (c <= 'f')) {
                nibble = c - 'a' + 0x0A;
            } else {
                throw new NumberFormatException("Invalid hex digit '" + c +
                        "'.");
            }

            if (evenByte) {
                nextByte = (byte) (nibble << 4);
            } else {
                nextByte += (byte) nibble;
                buffer[bufferOffset++] = nextByte;
            }

            evenByte = !evenByte;
        }

        return buffer;
    }

    public static byte[] bitmap2PrinterBytes_stylus(Bitmap bitmap, int multiple, int left) {
        int height = bitmap.getHeight();
        int width = bitmap.getWidth() + left;
        boolean need_0a = false;
        int maxWidth = 240;
        byte[] imgBuf;
        if (width < maxWidth) {
            imgBuf = new byte[(height / 8 + 1) * (width + 6)];
            need_0a = true;
        } else {
            imgBuf = new byte[(height / 8 + 1) * (width + 5) + 2];
        }

        byte[] tmpBuf = new byte[width + 5];
        int[] p = new int[8];
        int s = 0;
        boolean allZERO = true;

        int y;
        int i;
        for (y = 0; y < height / 8 + 1; ++y) {
            int t = 0;
            tmpBuf[t] = 27;
            t = t + 1;
            tmpBuf[t] = 42;
            ++t;
            tmpBuf[t] = (byte) multiple;
            ++t;
            tmpBuf[t] = (byte) (width % maxWidth);
            ++t;
            tmpBuf[t] = (byte) (width / maxWidth > 0 ? 1 : 0);
            allZERO = true;

            for (i = 0; i < width; ++i) {
                for (i = 0; i < 8; ++i) {
                    if (y * 8 + i < height && i >= left) {
                        p[i] = bitmap.getPixel(i - left, y * 8 + i) == -1 ? 0 : 1;
                    } else {
                        p[i] = 0;
                    }
                }

                i = p[0] * 128 + p[1] * 64 + p[2] * 32 + p[3] * 16 + p[4] * 8 + p[5] * 4 + p[6] * 2 + p[7];
                ++t;
                tmpBuf[t] = (byte) i;
                if (i != 0) {
                    allZERO = false;
                }
            }

            if (allZERO) {
                if (s == 0) {
                    imgBuf[s] = 27;
                } else {
                    ++s;
                    imgBuf[s] = 27;
                }

                ++s;
                imgBuf[s] = 74;
                ++s;
                imgBuf[s] = 8;
            } else {
                for (i = 0; i < t + 1; ++i) {
                    if (i == 0 && s == 0) {
                        imgBuf[s] = tmpBuf[i];
                    } else {
                        ++s;
                        imgBuf[s] = tmpBuf[i];
                    }
                }

                if (need_0a) {
                    ++s;
                    imgBuf[s] = 10;
                }
            }
        }

        if (!need_0a) {
            ++s;
            imgBuf[s] = 13;
            ++s;
            imgBuf[s] = 10;
        }

        byte[] realBuf = new byte[s + 1];

        for (y = 0; y < s + 1; ++y) {
            realBuf[y] = imgBuf[y];
        }

        StringBuffer sb = new StringBuffer();

        for (i = 0; i < realBuf.length; ++i) {
            String temp = Integer.toHexString(realBuf[i] & 255);
            if (temp.length() == 1) {
                temp = "0" + temp;
            }

            sb.append(temp + " ");
            if (i != 0 && i % 100 == 0 || i == realBuf.length - 1) {
                Log.e("12345", sb.toString());
                sb = new StringBuffer();
            }
        }

        return realBuf;
    }

    public static int getStringCharacterLength(String line) {
        int length = 0;

        for (int j = 0; j < line.length(); ++j) {
            if (line.charAt(j) > 256) {
                length += 2;
            } else {
                ++length;
            }
        }

        return length;
    }

    public static int getSubLength(String line, int width) {
        int length = 0;

        for (int j = 0; j < line.length(); ++j) {
            if (line.charAt(j) > 256) {
                length += 2;
            } else {
                ++length;
            }

            if (length > width) {
                int temp = line.substring(0, j - 1).lastIndexOf(" ");
                if (temp != -1) {
                    return temp;
                }

                return j - 1 == 0 ? 1 : j - 1;
            }
        }

        return line.length();
    }

    public static boolean isNum(byte temp) {
        return temp >= 48 && temp <= 57;
    }

    public static String wrap(String string, boolean is58mm,int widthType,int customLength) {

        int lineLength = 0;
        if (is58mm){
            switch (widthType){
                case DOUBLE_WIDTH:
                    lineLength = 16;
                    break;
                case NORMAL:
                case DOUBLE_HEIGHT:
                    lineLength = 32;
                    break;
                case CUSTOM:
                    lineLength = customLength;
                    break;
            }

        }else{
            switch (widthType){
                case DOUBLE_WIDTH:
                    lineLength = 23;
                    break;
                case NORMAL:
                case DOUBLE_HEIGHT:
                    lineLength = 46;
                    break;
                case CUSTOM:
                    lineLength = customLength;
                    break;
            }
        }


        StringBuilder b = new StringBuilder();
        for (String line : string.split(Pattern.quote(LINEBREAK))) {
            b.append(wrapLine(line, lineLength));
        }
        return b.toString();
    }

    private static String wrapLine(String line, int lineLength) {
        if (line.length() == 0) return LINEBREAK;
        if (line.length() <= lineLength) return line + LINEBREAK;
        String[] words = line.split(" ");
        StringBuilder allLines = new StringBuilder();
        StringBuilder trimmedLine = new StringBuilder();
        for (String word : words) {
            if (trimmedLine.length() + 1 + word.length() <= lineLength) {
                trimmedLine.append(word).append(" ");
            } else {
                allLines.append(trimmedLine).append(LINEBREAK);
                trimmedLine = new StringBuilder();
                trimmedLine.append(word).append(" ");
            }
        }
        if (trimmedLine.length() > 0) {
            allLines.append(trimmedLine);
        }
     //   allLines.append(LINEBREAK);
        return allLines.toString();
    }

}
