// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.pojo.ReceiptPojo;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.magilhub.printnats.desktop.render.legacy.framework.models.EodTipConfig;
import com.magilhub.printnats.desktop.render.legacy.framework.models.PaymentStatus;
import com.magilhub.printnats.desktop.render.legacy.framework.models.Receipt;

import com.magilhub.printnats.desktop.render.compat.json.JSONArray;
import com.magilhub.printnats.desktop.render.compat.json.JSONException;
import com.magilhub.printnats.desktop.render.compat.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

public class ReceiptPojo {
    private BusinessDetails businessDetails;
    private String orderNo;
    private String orderDate;

    private String etaTime;
    private String cardType;
    private String cardInfo;
    private String orderTime;
    private String serverStaffName;
    private String tableName;
    private String fullName;
    private String phone;
    private String comment;
    private String orderSourceName;
    private String orderTypeGroup;
    private boolean isAutoPrint;
    private Boolean isOrderCancelled;
    private List<ReceiptItem> items;
    private List<ReceiptItem> refundedItems;
    private List<ReceiptItem> voidedItems;
    private List<ReceiptItem> refundItems;
    private String refundedAmount;
    // Fee-component refunds ("Refunded Fee Comp", order activity status 109).
    // Already flattened by JS (buildRefundedFeeReceipt) so nothing has to be
    // JSON-parsed here; null when the order has no fee refund.
    private RefundedFee refundedFee;
    private List<Total> totals;
    private String paymentType;
    private String paymentlink;
    private String reviewQRLink;
    private String reviewMessage;
    // Pay-link QR for UNPAID receipts (generatePayQr) — distinct from the
    // IN-only UPI paymentlink. Empty/absent → QR block not rendered.
    private String payQrLink;
    // Accepted payment methods (restaurantDetails.cards) for the payment-logo
    // strip under the pay-link QR. Empty/absent → no strip.
    private List<String> cards;
    private PaymentStatus paymentStatus;
    private Footer footer;
    private boolean isCustomizationCountRequired;
    private List<Transaction> transactions;

    private String transactionStatusCode;

    private String kotNo;

    private String showKotNumber;
    private String showReceiptNo;
    private String showRestaurantName;

    private boolean isSalesOrder;

    private EodTipConfig eodTipConfig;

    private LoyaltyPointReceipt loyalty_point_receipt;

    public static class BusinessDetails {
        private String name;
        private String logo;
        private String caption;
        private String address;
        private String contactNumber;
        private String website;
        private String email;
        private String country;

        public String getName() { return name; }
        public String getLogo() { return logo; }
        public String getCaption() { return caption; }
        public String getAddress() { return address; }
        public String getContactNumber() { return contactNumber; }
        public String getWebsite() { return website; }
        public String getEmail() { return email; }
        public String getCountry() { return country; }
    }

    public static class ItemOption {
        private String optionName;
        private String quantity;
        private String price;
        // Sent only by v2/orders/item: quantity and price already multiplied out across the
        // option's own count and the parent item quantity. Null on every other payload, where
        // PrintUtil falls back to deriving both locally.
        private String actualQuantity;
        private Double actualPrice;

        public String getOptionName() { return optionName; }
        public String getQuantity() { return quantity; }
        public String getPrice() { return price; }
        public String getActualQuantity() { return actualQuantity; }
        public Double getActualPrice() { return actualPrice; }
    }

    public static class ReceiptItem {
        private String itemName;
        private String quantity;
        private double price;
        private String subTotal;
        private String comment;
        private List<ItemOption> options;
        private boolean isWeightBased;
        private String priceUnit;
        private boolean isFreeItem;
        private String redeemPoint;

        public String getItemName() { return itemName; }
        public String getQuantity() { return quantity; }
        public double getPrice() { return price; }
        public String getSubTotal() { return subTotal; }
        public String getComment() { return comment; }
        public List<ItemOption> getOptions() { return options; }
        public boolean getIsWeightBased() { return isWeightBased; }
        public String getPriceUnit() { return priceUnit; }
        public boolean getIsFreeItem() { return isFreeItem; }
        public String getRedeemPoint() { return redeemPoint; }

    }

    public static class Total {
        private String title;
        private String value;
        private String code;

        public String getTitle() { return title; }
        public String getCode() { return code; }
        public String getValue() { return value; }
    }

    public static class RefundedFeeLine {
        private String name;
        private String amount;

        public String getName() { return name; }
        public String getAmount() { return amount; }
    }

    public static class RefundedFee {
        private String title;
        private List<RefundedFeeLine> lines;
        private String totalAmount;
        private List<String> reasons;

        public String getTitle() { return title; }
        public List<RefundedFeeLine> getLines() { return lines; }
        public String getTotalAmount() { return totalAmount; }
        public List<String> getReasons() { return reasons; }
    }

    public static class LoyaltyPointReceiptTierAtOrder {
        private String tier_name;
        private String description;
        private Double multiplier;

        public String getTierName() { return tier_name; }
        public String getDescription() { return description; }
        public Double getMultiplier() { return multiplier; }
    }

    public static class LoyaltyPointReceiptProgram {
        private String name;
        private Boolean is_paused;

        public String getName() { return name; }
        public Boolean getIsPaused() { return is_paused; }
    }

    public static class LoyaltyPointReceiptPointsEarned {
        private Double total_points;

        public Double getTotalPoints() { return total_points; }
    }

    public static class LoyaltyPointReceiptPromotion {
        private String name;
        private Double multiplier_value;

        public String getName() { return name; }
        public Double getMultiplierValue() { return multiplier_value; }
    }

    public static class LoyaltyPointReceipt {
        private LoyaltyPointReceiptProgram program;
        private LoyaltyPointReceiptTierAtOrder tier_at_order;
        private LoyaltyPointReceiptPointsEarned points_earned;
        private Double balance_after;
        private String points_name;
        private List<LoyaltyPointReceiptPromotion> promotions_applied;

        public LoyaltyPointReceiptProgram getProgram() { return program; }
        public LoyaltyPointReceiptTierAtOrder getTierAtOrder() { return tier_at_order; }
        public LoyaltyPointReceiptPointsEarned getPointsEarned() { return points_earned; }
        public Double getBalanceAfter() { return balance_after; }
        public String getPointsName() { return points_name; }
        public List<LoyaltyPointReceiptPromotion> getPromotionsApplied() { return promotions_applied; }
    }

    public static class Footer {
        private String line1;

        public String getLine1() { return line1; }
    }

    public static class Transaction {
        private String tenderType;
        private double amountTendered;

        private String authorizationCode;

        private String retref;

        private String response;

        private String statusCode;


        public String getTenderType() { return tenderType; }
        public double getAmountTendered() { return amountTendered; }

        public String getAuthCode() { return authorizationCode; }

        public String getRefId() { return retref; }

        public String getResponse() { return response; }

        public String getStatusCode() { return statusCode; }

    }

    // Getters
    public BusinessDetails getBusinessDetails() { return businessDetails; }
    public EodTipConfig getEodTipConfig() { return eodTipConfig; }

    public String getOrderNo() { return orderNo; }
    public String getOrderDate() { return orderDate; }
    public String getOrderTime() { return orderTime; }
    public String getServerStaffName() { return serverStaffName; }
    public String getTableName() { return tableName; }
    public String getFullName() { return fullName; }
    public String getPhone() { return phone; }
    public String getComment() { return comment; }
    public String getOrderSourceName() { return orderSourceName; }
    public String getOrderTypeGroup() { return orderTypeGroup; }
    public boolean isAutoPrint() { return isAutoPrint; }
    public Boolean getIsOrderCancelled() { return isOrderCancelled; }
    public List<ReceiptItem> getItems() { return items; }
    public List<ReceiptItem> getRefundedItems() { return refundedItems; }
    public List<ReceiptItem> getVoidedItems() { return voidedItems; }
    public List<ReceiptItem> getRefundItems() { return refundItems; }
    public String getRefundedAmount() { return refundedAmount; }
    public RefundedFee getRefundedFee() { return refundedFee; }
    public List<Total> getTotals() { return totals; }
    public String getPaymentType() { return paymentType; }
    public String getPaymentlink() { return paymentlink; }
    public String getReviewQRLink() { return reviewQRLink; }
    public String getReviewMessage() { return reviewMessage; }
    public String getPayQrLink() { return payQrLink; }
    public List<String> getCards() { return cards; }
    public PaymentStatus getPaymentStatus() { return paymentStatus; }
    public Footer getFooter() { return footer; }
    public boolean isCustomizationCountRequired() { return isCustomizationCountRequired; }
    public boolean getIsSalesOrder() { return isSalesOrder; }
    public List<Transaction> getTransactions() { return transactions; }
    public String getEtaTime() { return etaTime; }

    public String getCardInfo() {
        return cardInfo;
    }

    public String getCardType() {
        return cardType;
    }
    public String getTransactionStatusCode() {
        return transactionStatusCode;
    }

    public String getKotNo() {
        return kotNo;
    }

    public String getShowKotNumber() {
        return showKotNumber;
    }

    public String getShowReceiptNo() {
        return showReceiptNo;
    }

    public String getShowRestaurantName() {
        return showRestaurantName;
    }

    public LoyaltyPointReceipt getLoyaltyPointReceipt() {
        return loyalty_point_receipt;
    }
}
