#!/usr/bin/env bash
# Regenerates desktop/.../render/legacy/** from the Android adapter's mechanical copy of MerchantApp's print code
# (android/.../android/legacy/**). Only package names and android.* / org.json / androidx.annotation imports are
# rewritten (to the Java2D compat layer in desktop/.../render/compat); the Java code itself is left verbatim.
#
# Usage (from anywhere):  bash desktop/src/main/java/com/magilhub/printnats/desktop/render/legacy/copy-from-android.sh
#
# Hand-written files in legacy/ that this script never touches: logging/LogFileAppender.java (desktop no-op sink).
# Everything else under legacy/ is overwritten. See docs/desktop-receipt-port-notes.md.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../../../../../../../../.." && pwd)"
SRC="$ROOT/android/src/main/java/com/magilhub/printnats/android/legacy"
DST="$HERE"

[ -d "$SRC" ] || { echo "source not found: $SRC" >&2; exit 1; }

# Files needed for receipt (image + text) and EOD rendering. Deliberately NOT copied:
#   escpos/connection/{bluetooth,usb,tcp}/**  (Android transports; the desktop renderer captures bytes in memory)
#   framework/models/StarStatusDTO.java       (Star SDK type, unused by receipts/EOD)
#   framework/db/entity/PrintEntity.java       (Room entity; PrintUtil only imports it)
#   logging/LogFileAppender.java               (Android file logger -> hand-written desktop replacement)
FILES=$(cd "$SRC" && find escpos framework -name '*.java' \
    ! -path 'escpos/connection/bluetooth/*' \
    ! -path 'escpos/connection/usb/*' \
    ! -path 'escpos/connection/tcp/*' \
    ! -name 'StarStatusDTO.java' \
    ! -name 'PrintEntity.java' | sort)

# Clean previous copy (keep hand-written logging/ and this script).
rm -rf "$DST/escpos" "$DST/framework"

for f in $FILES; do
    mkdir -p "$DST/$(dirname "$f")"
    perl -pe '
        s{^// Copied mechanically from MerchantApp.*}{// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).} if $. == 1;
        s{^// Only package names and R were rewritten.*}{// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.} if $. == 2;
        s{com\.magilhub\.printnats\.android\.legacy}{com.magilhub.printnats.desktop.render.legacy}g;
        s{com\.magilhub\.printnats\.android\.R\b}{COMPAT.R}g;
        $_ = "" if /^import androidx\.room\.FtsOptions;/;
        $_ = "" if /^import com\.magilhub\.printnats\.desktop\.render\.legacy\.framework\.db\.entity\.PrintEntity;/;
        s{\bandroid\.graphics\.drawable\.}{COMPAT.}g;
        s{\bandroid\.(graphics|content|util|text|os)\.}{COMPAT.}g;
        s{\bandroidx\.annotation\.}{COMPAT.}g;
        s{\borg\.json\.}{COMPAT.json.}g;
        s{COMPAT}{com.magilhub.printnats.desktop.render.compat}g;
    ' "$SRC/$f" > "$DST/$f"
done

echo "copied $(echo "$FILES" | wc -l | tr -d ' ') files into $DST"
