// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class CardPaymentRequest {
    @SerializedName("locationId")
    @Expose
    private String locationId;
    @SerializedName("accountNumber")
    @Expose
    private String accountNumber;
    @SerializedName("expiry")
    @Expose
    private String expiry;
    @SerializedName("postalCode")
    @Expose
    private String postalCode;
    @SerializedName("tenderType")
    @Expose
    private String tenderType;
    @SerializedName("orderId")
    @Expose
    private String orderId;
    @SerializedName("totalPaymentAmount")
    @Expose
    private Double totalPaymentAmount;
    @SerializedName("paymentCurrency")
    @Expose
    private String paymentCurrency;

    public String getLocationId() {
        return locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getExpiry() {
        return expiry;
    }

    public void setExpiry(String expiry) {
        this.expiry = expiry;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getTenderType() {
        return tenderType;
    }

    public void setTenderType(String tenderType) {
        this.tenderType = tenderType;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public Double getTotalPaymentAmount() {
        return totalPaymentAmount;
    }

    public void setTotalPaymentAmount(Double totalPaymentAmount) {
        this.totalPaymentAmount = totalPaymentAmount;
    }

    public String getPaymentCurrency() {
        return paymentCurrency;
    }

    public void setPaymentCurrency(String paymentCurrency) {
        this.paymentCurrency = paymentCurrency;
    }
}
