// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class EodReport {

    @SerializedName("orderReport")
    @Expose
    OrderReport orderReport;

    @SerializedName("paymentReport")
    @Expose
    PaymentReport paymentReport;

    @SerializedName("header")
    @Expose
    EODHeader eodHeader;


    public OrderReport getOrderReport() {
        return orderReport;
    }

    public void setOrderReport(OrderReport orderReport) {
        this.orderReport = orderReport;
    }

    public PaymentReport getPaymentReport() {
        return paymentReport;
    }

    public void setPaymentReport(PaymentReport paymentReport) {
        this.paymentReport = paymentReport;
    }

    public EODHeader getEodHeader() {
        return eodHeader;
    }
}
