// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

public class EODRow {

    String title,count,total;
    boolean isDashedLine = false;


    public EODRow(String title, String count, String total) {
        this.title = title;
        this.count = count;
        this.total = total;
        isDashedLine = false;
    }

    public EODRow(boolean isDashedLine) {
        this.isDashedLine = isDashedLine;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    public boolean isDashedLine() {
        return isDashedLine;
    }

    public void setDashedLine(boolean dashedLine) {
        isDashedLine = dashedLine;
    }
}
