// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import java.util.ArrayList;
import java.util.List;


public class EodTipConfig {
    private List<Integer> percents = new ArrayList<>();
    private List<TipOption> fixedAmounts = new ArrayList<>();
    private String currencySymbol = "$";
    private boolean isEodTipEnabled;
  private boolean isTransactionReceipt;

    public EodTipConfig() {}


    public EodTipConfig(List<Integer> percents, List<TipOption> fixedAmounts, String currencySymbol, boolean isEodTipEnabled, boolean isTransactionReceipt) {
        if (percents != null) this.percents = percents;
        if (fixedAmounts != null) this.fixedAmounts = fixedAmounts;
        if (currencySymbol != null) this.currencySymbol = currencySymbol;
        this.isEodTipEnabled = isEodTipEnabled;
        this.isTransactionReceipt = isTransactionReceipt;
    }


    public List<Integer> getPercents() {
        return percents;
    }


    public void setPercents(List<Integer> percents) {
        this.percents = percents;
    }


    public List<TipOption> getFixedAmounts() {
        return fixedAmounts;
    }


    public void setFixedAmounts(List<TipOption> fixedAmounts) {
        this.fixedAmounts = fixedAmounts;
    }


    public String getCurrencySymbol() {
        return currencySymbol;
    }


    public void setCurrencySymbol(String currencySymbol) {
        this.currencySymbol = currencySymbol;
    }


    public boolean isEodTipEnabled() {
        return isEodTipEnabled;
    }

    public boolean isTransactionReceipt() {
        return isTransactionReceipt;
    }


    public void setTransactionReceipt(boolean transactionReceipt) {
        isTransactionReceipt = transactionReceipt;
    }

    public void setEodTipEnabled(boolean eodTipEnabled) {
        isEodTipEnabled = eodTipEnabled;
    }


    @Override
    public String toString() {
        return "EodTipConfig{" +
                "percents=" + percents +
                ", fixedAmounts=" + fixedAmounts +
                ", currencySymbol='" + currencySymbol + '\'' +
                ", isEodTipEnabled=" + isEodTipEnabled +
                ", isTransactionReceipt=" + isTransactionReceipt +
                '}';
    }
}