// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.List;

public class ItemReport {

    @SerializedName("totalItemCount")
    @Expose
    int totalItemCount;

    @SerializedName("subTotal")
    @Expose
    String subTotal;

    @SerializedName("categoryName")
    @Expose
    String categoryName;

    @SerializedName("itemReports")
    @Expose
    List<ReportItems> reportItems;


    public int getTotalItemCount() {
        return totalItemCount;
    }

    public String getSubTotal() {
        return subTotal;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public List<ReportItems> getReportItems() {
        return reportItems;
    }
}
