// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class Option {

    @SerializedName("id")
    @Expose
    String id;

    @SerializedName("modifierOptionId")
    @Expose
    String modifierOptionId;

    @SerializedName("optionName")
    @Expose
    String optionName;

    @SerializedName("quantity")
    @Expose
    String quantity;

    @SerializedName("price")
    @Expose
    String price;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getModifierOptionId() {
        return modifierOptionId;
    }

    public void setModifierOptionId(String modifierOptionId) {
        this.modifierOptionId = modifierOptionId;
    }

    public String getOptionName() {
        return optionName;
    }

    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }

    public String getQuantity() {
        return quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }
}
