// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class OrderReport {


    @SerializedName("Success Orders")
    @Expose
    Orders successOrders;

    @SerializedName("Cancelled Orders")
    @Expose
    Orders cancelledOrders;

    @SerializedName("Complimentary Orders")
    @Expose
    Orders complimentaryOrders;

    @SerializedName("Online Orders")
    @Expose
    Orders onlineOrders;


    public Orders getSuccessOrders() {
        return successOrders;
    }

    public void setSuccessOrders(Orders successOrders) {
        this.successOrders = successOrders;
    }

    public Orders getCancelledOrders() {
        return cancelledOrders;
    }

    public void setCancelledOrders(Orders cancelledOrders) {
        this.cancelledOrders = cancelledOrders;
    }

    public Orders getComplimentaryOrders() {
        return complimentaryOrders;
    }

    public void setComplimentaryOrders(Orders complimentaryOrders) {
        this.complimentaryOrders = complimentaryOrders;
    }

    public Orders getOnlineOrders() {
        return onlineOrders;
    }
}
