// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.SerializedName;

public class OrderPaymentDetail {
    @SerializedName("paymentMethod") private String paymentMethod;
    @SerializedName("value") private String value;

    public String getPaymentMethod() { return paymentMethod; }
    public String getValue() { return value; }
}
