// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.List;

public class PaymentReport {

    @SerializedName(value = "Order Payment Details",
            alternate = {"orderPaymentDetails","order_payment_details"})
    private List<OrderPaymentDetail> orderPaymentDetails;

    @SerializedName(value = "Payment Information",
            alternate = {"paymentInformation","payment_information"})
    private List<TitleValue> paymentInformation;

    public List<OrderPaymentDetail> getOrderPaymentDetails() { return orderPaymentDetails; }
    public List<TitleValue> getPaymentInformation() { return paymentInformation; }


}
