// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

public class TipOption {
    private int percent;        // Tip percentage (e.g. 20)
    private double tipAmount;   // Calculated tip value (e.g. 40.00)
    private double totalAmount; // Total = orderTotal + tipAmount

    public TipOption() {}

    public TipOption(int percent, double tipAmount, double totalAmount) {
        this.percent = percent;
        this.tipAmount = tipAmount;
        this.totalAmount = totalAmount;
    }

    public int getPercent() {
        return percent;
    }

    public void setPercent(int percent) {
        this.percent = percent;
    }

    public double getTipAmount() {
        return tipAmount;
    }

    public void setTipAmount(double tipAmount) {
        this.tipAmount = tipAmount;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Override
    public String toString() {
        return "TipOption{" +
                "percent=" + percent +
                ", tipAmount=" + tipAmount +
                ", totalAmount=" + totalAmount +
                '}';
    }
}
