// GENERATED by render/legacy/copy-from-android.sh from android/.../legacy (itself copied from MerchantApp).
// Only package names and android.*/org.json/androidx imports were rewritten - do not hand-edit; re-run the script.
package com.magilhub.printnats.desktop.render.legacy.framework.models;

import com.google.gson.annotations.SerializedName;

public class TitleValue {
    @SerializedName("title") private String title;
    @SerializedName("value") private String value; // or double if numeric-only

    public String getTitle() { return title; }
    public String getValue() { return value; }
}
